// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/register","layout":false,"id":"2"},"3":{"path":"/","id":"3"},"4":{"path":"/dashboard","title":"仪表盘","parentId":"3","id":"4"},"5":{"path":"/profile","title":"个人资料","parentId":"3","id":"5"},"6":{"path":"/","redirect":"/dashboard","parentId":"3","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__register" */'@/pages/register.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__MainLayout" */'@/layouts/MainLayout.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__dashboard" */'@/pages/dashboard.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__profile" */'@/pages/profile.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
},
  };
}
