// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/register","layout":false,"id":"2"},"3":{"path":"/","id":"3"},"4":{"path":"/dashboard","title":"仪表盘","parentId":"3","id":"4"},"5":{"path":"/news","title":"新闻列表","parentId":"3","id":"5"},"6":{"path":"/news/:id","title":"新闻详情","parentId":"3","id":"6"},"7":{"path":"/signals","title":"信号列表","parentId":"3","id":"7"},"8":{"path":"/signals/:id","title":"信号详情","parentId":"3","id":"8"},"9":{"path":"/backtest","title":"回测分析","parentId":"3","id":"9"},"10":{"path":"/settings/notifications","title":"通知设置","parentId":"3","id":"10"},"11":{"path":"/settings/scheduler","title":"定时任务","parentId":"3","id":"11"},"12":{"path":"/profile","title":"个人资料","parentId":"3","id":"12"},"13":{"path":"/","redirect":"/dashboard","parentId":"3","id":"13"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__register" */'@/pages/register.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__MainLayout" */'@/layouts/MainLayout.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__dashboard" */'@/pages/dashboard.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__news__index" */'@/pages/news/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__news__id" */'@/pages/news/[id].tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__signals__index" */'@/pages/signals/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__signals__id" */'@/pages/signals/[id].tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__backtest__index" */'@/pages/backtest/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__settings__notifications" */'@/pages/settings/notifications.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__settings__scheduler" */'@/pages/settings/scheduler.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__profile" */'@/pages/profile.tsx')),
'13': React.lazy(() => import('./EmptyRoute')),
},
  };
}
